services:
  testMongo1:
    image: mongo:6.0.6
    container_name: testMongo1
    command: mongod --replSet testReplica --bind_ip_all
    ports:
      - '27017:27017'
    networks:
      - testNet

networks:
  testNet:
    driver: bridge